export type Country = {
  id: string;
  code: string;
  name: string;
  region: string;
  lat: number;
  long: number;
  hiddenSongs: number;
  genres: string[];
  album: string;
  albumArtist: string;
  hasSongData?: boolean;
  topSong: string;
  languages: string[];
  sceneNote: string;
  featuredArtists: string[];
  markerTop: string;
  markerLeft: string;
};

export type Song = {
  id: string;
  title: string;
  artist: string;
  album: string;
  deezerTrackId?: number;
  deezerAlbumId?: number;
  deezerArtistId?: number;
  albumArtUrl?: string;
  artistImageUrl?: string;
  explicitLyrics?: boolean;
  explicitContentCover?: boolean;
  albumExplicitLyrics?: boolean;
  releaseDate?: string;
  recordType?: string;
  contributors?: string[];
  artistAlbumCount?: number;
  tracklist?: string[];
  genres: string[];
  languages: string[];
  year: number;
  duration: string;
  description: string;
  spotifySearchUrl: string;
};
